export interface Ride{
    applicatioId:number,
    destCity:string,
    destStreet:string,
    destHouseNum:Number,
    destlatitude:string,
    destLongitude:string,
    endPeriod:string,
    userId:Number,
    period:string,
    city:string,
    street: string,
    houseNumber:Number,
    latitude:string,
    Longitude:string,
    periodic:string,
    urgency:Boolean,
    status:string,
    isAprroved:Boolean,
    gender:string,
    language:string,
    img:string,
    title:string,
    description:string
}
